import type { Metadata } from 'next';

import '@/assets/styles/globals.css';
import inter from '@/assets/fonts/inter';

export const metadata: Metadata = {
  'title': 'Create Next App',
  'description': 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>{children}</body>
    </html>
  );
}
